name: First Workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
    # targeted branch
    # to what brach, not from what branch
    branches:
      - main
  push:
    # if last commit in the end of commit message has [skip ci] (or similar, see Skip workflows run) then it will not trigger wrkflow this time
    # targeted branch
    branches:
      - main #main
      - 'feat/**' #feat/new feat/new/button
      - 'dev-*' #dev-new dev-this-is-new
    #you can only define one of paths and paths-ignore for a single event
    #paths:
      #- '.github/*' #needs at least one file from there changed
    paths-ignore:
      - '.github/workflows/*' #do nothing if at leadt one file from there is changed
      #those paths for events filters work if AT LEAST ONE FILE
env:
  my-variable: workflow-value-here #scope in whole workflow, when the same var name is in job then it uses local variable
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: |
          echo "bye"
          echo "bye bye"
      - name: Using step env
        env: 
          my-step-var: step-value-here
        run: |
          echo "step var: $my-step-var"
          echo "step var: ${{ env.my-step-var }}"
  second-job:
    needs: first-job
    env:
      my-job-variable: job-value-here #scope only in the job
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Print variables
        run: |
          echo "my-variable: $my-variable"
          echo "my-variable: ${{ env.my-variable }}"
          echo "my-job-variable: $my-job-variable"
          echo "my-job-variable: ${{ env.my-job-variable }}"
  third-job:
    needs: [ second-job ]
    runs-on: ubuntu-latest
    steps:
      - name: download repository code on runner
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: readme-file
          path: README.md
  fourth-job:
    needs: third-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: readme-file
      - name: Show files
        run: ls
    


